// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Locker is an autogenerated mock type for the Locker type
type Locker struct {
	mock.Mock
}

// Lock provides a mock function with given fields: stopChan
func (_m *Locker) Lock(stopChan chan struct{}) (<-chan struct{}, error) {
	ret := _m.Called(stopChan)

	var r0 <-chan struct{}
	if rf, ok := ret.Get(0).(func(chan struct{}) <-chan struct{}); ok {
		r0 = rf(stopChan)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan struct{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(chan struct{}) error); ok {
		r1 = rf(stopChan)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Unlock provides a mock function with given fields:
func (_m *Locker) Unlock() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
