name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Lint
      run: make lint
    
    - name: Tests
      run: make test

    - name: Lint v2
      run: make lintv2

    - name: Test v2
      run: make testv2
